language: java
jdk:
  - oraclejdk8

services:
  - mysql

before_install:
  - mysql -u root -e "CREATE USER 'admin'@'localhost' IDENTIFIED BY 'admin'; GRANT ALL PRIVILEGES ON *.* TO 'admin'@'localhost' WITH GRANT OPTION; ";
  - mysql -u root "--password=" < resources/initialization.sql

